### ISSUE TITLE
Implementing FTelnet in windows

### ISSUE THREAD

**Issue by nthompson0033** [rickparrish/my.fTelnet.ca#1]
Hi I have a soft PLC (Accos) that hosts dynamic text displays using telnet clients such as TeraTerm VT100 or other.

The Soft PLC code is flexible in terms of emulation mode and screen size, but showing dynamic
text fields is important.

The web server need to run on the same local network as the soft PLC systems

I have downloaded FTelnet with a view to hosting telnet connections through Android/Iphone etc's web interface, would FTelnet be applicable to this application

I also saw the flash version would this be more applicable and is it supported by Apple?
is the flash version a commercial product 

When I open the solution in VS2013 I cannot compile FTelnet? It shows the errors below.

Hoping you can help in any way Nick.

Error   1   The command "copy C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\release\IELessThan9Check.js + C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\release\Blob.js + C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\release\FileSaver.js + C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\release\ftelnet.debug.js C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\release\ftelnet.combined.js
jsmin <C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\release\ftelnet.combined.js >C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\release\ftelnet.min.js" exited with code 9009.    fTelnet
Error   2   Interface 'Window' cannot extend interface 'MSWindowExtensions':
    Types of property 'clipboardData' of types 'Window' and 'MSWindowExtensions' are incompatible:
        Type 'ClipboardData' is missing property 'effectAllowed' from type 'DataTransfer'.  lib.d.ts    3486    11  fTelnet
Error   3   The property 'fullscreenElement' does not exist on value of type 'Document'.    C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\source\fTelnet.ts  491 23  fTelnet
Error   4   The property 'webkitFullscreenElement' does not exist on value of type 'Document'.  C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\source\fTelnet.ts  491 88  fTelnet
Error   5   The property 'exitFullscreen' does not exist on value of type 'Document'.   C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\source\fTelnet.ts  503 26  fTelnet
Error   6   The property 'exitFullscreen' does not exist on value of type 'Document'.   C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\source\fTelnet.ts  504 26  fTelnet
Error   7   The property 'webkitExitFullscreen' does not exist on value of type 'Document'. C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\source\fTelnet.ts  509 33  fTelnet
Error   8   The property 'webkitExitFullscreen' does not exist on value of type 'Document'. C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\source\fTelnet.ts  510 26  fTelnet
Error   9   Duplicate identifier 'msExitFullscreen'.    C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\source\3rdparty\Document.d.ts  8   5   fTelnet
Error   10  Duplicate identifier 'msFullscreenElement'. C:\DownloadSrc\FTelnet\fTelnet-master\fTelnet-master\source\3rdparty\Document.d.ts  9   5   fTelnet

**Comment by rickparrish** [comment]
What version of "TypeScript for Microsoft Visual Studio" do you have installed?  You can see that by clicking Tools -> Extensions and Updates.  I'm guessing it's an older version, and if that's the case updating to the latest (1.6.3) should solve the problem (I just updated to that here, and tested to ensure everything still builds)

As for whether fTelnet would work -- presumably the PLC does not speak WebSocket, so fTelnet will not be able to connect to it directly.  This means you'll need to run a proxy (like https://github.com/rickparrish/fTelnetProxy) to allow fTelnet to connect to the PLC.  

As long as the proxy runs on a machine that can connect to the PLC, and can also be connected to via the android/iphone devices, then yes fTelnet should work.  That said it's optimized for BBS use, so I can't guarantee the display will be correct if the PLC sends unsupported commands.  Doesn't hurt to try though!

Neither the old flash or new javascript versions of the client are commercial, but they do need permission if you'll be redistributing them in a commercial product.  If it's just for your own personal use though, then they're both totally free.

**Comment by nthompson0033** [comment]
Thankyou I will try this.
